#!/bin/sh

cd $(dirname $0)
config=config.default
if [ -f "config.custom" ]; then
    config=config.custom
fi

chmod +x $config

if ! sh $config; then
    echo "failed generate config with $config"
    exit 1
fi

for m in $(tac /proc/mounts | awk '{print $2}' | grep /containers/.*/shm$); do
        umount $m || true
done

/pilot/pilot -base /host -template /pilot/fluentd.tpl -log-level debug

